# Generates and validates the Rivulet Chocolatey package for a GitHub release.
#
# Chocolatey (community repository) accepts unsigned installers, but unlike
# Scoop the submission is a moderated pull request against
# community-chocolatey/chocolatey-core-repo — so this generator produces a
# dry-run package directory that a maintainer can submit once the release
# cadence justifies it (first beta). The package wraps the portable ZIP
# asset and pins it by the SHA-256 from the release's SHA256SUMS asset; it
# never trusts the files it validates by re-rendering and comparing.
#
# Chocolatey does not allow dots inside a prerelease suffix, so the version
# is normalized for the nuspec: 0.65.0-alpha.163 -> 0.65.0-alpha163.
#
# Usage:
#   # From a real release (takes the SHA-256 from the release's SHA256SUMS
#   # asset, verifying the ZIP is listed there):
#   pwsh packaging/windows/generate-chocolatey-package.ps1 `
#       -Version 0.65.0-alpha.163 -ReleaseTag v0.65.0-alpha.163 -OutDir out
#
#   # Deterministic/offline (any OS; SHA-256 supplied by caller):
#   pwsh packaging/windows/generate-chocolatey-package.ps1 `
#       -Version 0.65.0-alpha.55 -ReleaseTag v0.65.0-alpha.55 `
#       -ZipSha256 <64 hex> -OutDir out
#
#   # Re-verify an existing package directory (re-render + byte compare):
#   pwsh packaging/windows/generate-chocolatey-package.ps1 -ValidateOnly `
#       -ManifestPath out/rivulet `
#       -Version 0.65.0-alpha.55 -ReleaseTag v0.65.0-alpha.55 -ZipSha256 <64 hex>
#
# The generated layout is drop-in for the chocolatey-core-repo submission:
#   out/rivulet/rivulet.nuspec
#   out/rivulet/tools/chocolateyInstall.ps1

param(
  [Parameter(Mandatory = $true)][string]$Version,
  [string]$ReleaseTag,
  [string]$ZipSha256,
  [string]$Repo = "thoser666/Rivulet",
  [string]$PackageId = "rivulet",
  [string]$Publisher = "Rivulet",
  [string]$License = "MIT",
  [string]$LicenseUrl = "https://github.com/thoser666/Rivulet/blob/develop/LICENSE",
  [string]$OutDir = "chocolatey-packages",
  [switch]$ValidateOnly,
  [string]$ManifestPath
)

$ErrorActionPreference = "Stop"
$tag = if ($ReleaseTag) { $ReleaseTag } else { "v$Version" }

function Assert-ValidSha256 {
  param([string]$Sha, [string]$What)
  if ($Sha -notmatch '^[0-9a-f]{64}$') {
    throw "$What must be a 64-char lowercase hex SHA-256, got: '$Sha'"
  }
}

# Chocolatey prerelease suffixes must not contain dots; keep the winget
# input contract (x.y.z-(alpha|beta|rc).N) and flatten for the nuspec.
function ConvertTo-ChocolateyVersion {
  param([string]$SemVer)
  $normalized = $SemVer -replace '-(alpha|beta|rc)\.(\d+)$', '-$1$2'
  if ($normalized -notmatch '^\d+\.\d+\.\d+(-(alpha|beta|rc)\d+)?$') {
    throw "Version must look like x.y.z or x.y.z-(alpha|beta|rc).N, got '$SemVer'"
  }
  return $normalized
}

function Get-ZipSha256FromRelease {
  param([string]$Repo, [string]$Tag, [string]$AssetName)
  if (-not (Get-Command gh -ErrorAction SilentlyContinue)) {
    throw "gh CLI not found; pass -ZipSha256 explicitly for offline rendering"
  }
  $tmp = Join-Path ([IO.Path]::GetTempPath()) ("rivulet-choco-shasums-" + [Guid]::NewGuid().ToString("N"))
  New-Item -ItemType Directory -Force -Path $tmp | Out-Null
  try {
    & gh release download $Tag --repo $Repo --pattern SHA256SUMS --dir $tmp | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "failed to download SHA256SUMS for $Tag" }
    $sumsFile = Join-Path $tmp "SHA256SUMS"
    if (-not (Test-Path $sumsFile)) { throw "release $Tag has no SHA256SUMS asset" }
    $line = Select-String -LiteralPath $sumsFile -Pattern ('^([0-9a-f]{64})\s+\*?' + [regex]::Escape($AssetName) + '\s*$') |
      Select-Object -First 1
    if (-not $line) {
      throw "SHA256SUMS for $Tag does not list '$AssetName' — refusing to render an unverified package"
    }
    return $line.Matches[0].Groups[1].Value
  }
  finally {
    Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue
  }
}

$assetName = "rivulet-windows-x86_64-portable.zip"
$zipUrl = "https://github.com/$Repo/releases/download/$tag/$assetName"
$releaseNotesUrl = "https://github.com/$Repo/releases/tag/$tag"

if (-not $ZipSha256) {
  $ZipSha256 = Get-ZipSha256FromRelease -Repo $Repo -Tag $tag -AssetName $assetName
}
$ZipSha256 = $ZipSha256.ToLowerInvariant()
Assert-ValidSha256 -Sha $ZipSha256 -What "-ZipSha256 / SHA256SUMS hash"
$chocoVersion = ConvertTo-ChocolateyVersion -SemVer $Version

function Render-Nuspec {
  return @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by packaging/windows/generate-chocolatey-package.ps1 — do not edit by hand. -->
<package xmlns="http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd">
  <metadata>
    <id>$PackageId</id>
    <version>$chocoVersion</version>
    <title>Rivulet</title>
    <authors>$Publisher contributors</authors>
    <owners>$Publisher</owners>
    <licenseUrl>$LicenseUrl</licenseUrl>
    <projectUrl>https://github.com/$Repo</projectUrl>
    <projectSourceUrl>https://github.com/$Repo</projectSourceUrl>
    <packageSourceUrl>https://github.com/$Repo</packageSourceUrl>
    <bugTrackerUrl>https://github.com/$Repo/issues</bugTrackerUrl>
    <releaseNotes>$releaseNotesUrl</releaseNotes>
    <iconUrl>https://raw.githubusercontent.com/$Repo/develop/docs/assets/rivulet-rich-presence-1024.png</iconUrl>
    <summary>Open-source screen recorder and live streaming studio</summary>
    <description>Rivulet is an open-source screen recorder and live streaming studio with OBS-compatible automation (obs-websocket), multi-platform chat, Discord Rich Presence, and privacy-first telemetry. The package installs the portable bundle with a bundled GStreamer runtime.</description>
    <tags>streaming broadcast screen-recorder recording obs twitch capture</tags>
    <copyright>Copyright Rivulet contributors</copyright>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <docsUrl>https://github.com/$Repo/blob/develop/docs/</docsUrl>
  </metadata>
</package>
"@
}

function Render-InstallScript {
  return @"
# Generated by packaging/windows/generate-chocolatey-package.ps1 — do not edit by hand.
`$ErrorActionPreference = 'Stop'

`$toolsDir = Split-Path -Parent `$MyInvocation.MyCommand.Definition
`$packageArgs = @{
  packageName   = `$env:ChocolateyPackageName
  unzipLocation = `$toolsDir
  url64bit      = '$zipUrl'

  checksum64    = '$ZipSha256'
  checksumType64 = 'sha256'
}

Install-ChocolateyZipPackage @packageArgs

Write-Host "Rivulet is installed as a portable bundle with a bundled GStreamer runtime."
Write-Host "Start it with rivulet-gui.exe in `$toolsDir, or add that folder to your PATH."
"@
}

if ($ValidateOnly) {
  if (-not $ManifestPath) { throw "-ValidateOnly requires -ManifestPath" }
  $pkgDir = $ManifestPath
  $nuspecPath = Join-Path $pkgDir "$PackageId.nuspec"
  $installPath = Join-Path $pkgDir "tools/chocolateyInstall.ps1"
  foreach ($file in @($nuspecPath, $installPath)) {
    if (-not (Test-Path -LiteralPath $file)) {
      throw "package drift: $file is missing"
    }
  }
  $pairs = @(
    @{ Path = $nuspecPath; Expected = (Render-Nuspec) },
    @{ Path = $installPath; Expected = (Render-InstallScript) }
  )
  foreach ($pair in $pairs) {
    $actual = (Get-Content -LiteralPath $pair.Path -Raw) -replace "`r`n", "`n"
    $expected = $pair.Expected -replace "`r`n", "`n"
    if ($expected -ne $actual) {
      throw "package drift: $($pair.Path) does not match the expected render for version $Version (tag $tag, sha $ZipSha256)"
    }
  }
  # Structural sanity: XML must parse and the fields Chocolatey moderation
  # checks must survive.
  [xml]$nuspec = Get-Content -LiteralPath $nuspecPath -Raw
  foreach ($field in @("id", "version", "title", "description", "projectUrl", "licenseUrl", "tags")) {
    $node = $nuspec.package.metadata.$field
    if (-not $node -or -not "$node".Trim()) {
      throw "package drift: required nuspec field '$field' missing or empty in $nuspecPath"
    }
  }
  $install = Get-Content -LiteralPath $installPath -Raw
  foreach ($needle in @("Install-ChocolateyZipPackage", $zipUrl, "checksumType64 = 'sha256'")) {
    if (-not $install.Contains($needle)) {
      throw "package drift: install script is missing '$needle'"
    }
  }
  Write-Output "OK package verified: $pkgDir"
  exit 0
}

$pkgDir = Join-Path $OutDir $PackageId
$toolsDir = Join-Path $pkgDir "tools"
$installPath = Join-Path $toolsDir "chocolateyInstall.ps1"
New-Item -ItemType Directory -Force -Path $toolsDir | Out-Null
[System.IO.File]::WriteAllText((Join-Path $pkgDir "$PackageId.nuspec"), (Render-Nuspec))
[System.IO.File]::WriteAllText($installPath, (Render-InstallScript))
Write-Output "Wrote $pkgDir ($PackageId.nuspec + tools/chocolateyInstall.ps1)"
Write-Output "Submission: open a moderated PR against the Chocolatey community repository with this package directory."
