#!/usr/bin/env bash
# Creates the Rivulet.app bundle in the staging directory from the staged
# release binary. The bundle is later packaged into a DMG by build-dmg.sh
# (unsigned) or sign-notarize.sh (signed + notarized).
#
# Usage: packaging/macos/build-app.sh <version> <staging-dir>
set -euo pipefail

VERSION="${1:?Missing version}"
STAGING="${2:?Missing staging directory}"

APP="$STAGING/Rivulet.app"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cp "$STAGING/rivulet-gui" "$APP/Contents/MacOS/rivulet-gui"
chmod +x "$APP/Contents/MacOS/rivulet-gui"

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Rivulet</string>
  <key>CFBundleDisplayName</key><string>Rivulet</string>
  <key>CFBundleIdentifier</key><string>com.rivulet.app</string>
  <key>CFBundleVersion</key><string>$VERSION</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleExecutable</key><string>rivulet-gui</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>LSMinimumSystemVersion</key><string>11.0</string>
  <key>NSHighResolutionCapable</key><true/>
  <key>CFBundleIconFile</key><string>AppIcon</string>
</dict>
</plist>
EOF

# App icon, generated by scripts/generate-assets.sh (see README "Assets").
if [[ -f "packaging/rivulet.icns" ]]; then
  cp packaging/rivulet.icns "$APP/Contents/Resources/AppIcon.icns"
else
  echo "warning: packaging/rivulet.icns missing; using the generic app icon" >&2
fi

# Ship the Discord Rich Presence setup assets (app icon for the member list,
# Rich Presence artwork for the profile card) and the setup documentation so
# users can complete the Discord configuration without the repository.
DOCDIR="$APP/Contents/Resources/discord"
mkdir -p "$DOCDIR/assets"
for pair in \
  "docs/assets/rivulet-app-icon-512.png:rivulet-app-icon-512.png" \
  "docs/assets/rivulet-rich-presence-1024.png:rivulet-rich-presence-1024.png" \
  "docs/assets/rivulet-rich-presence-512.png:assets/rivulet-rich-presence-512.png" \
  "docs/activity-status.md:activity-status.md"; do
  src="${pair%%:*}"
  dst="${pair##*:}"
  if [[ -f "$src" ]]; then
    cp "$src" "$DOCDIR/$dst"
  else
    echo "warning: Discord asset missing, skipped: $src" >&2
  fi
done

chmod -R u+rwX "$APP"
echo "App bundle created: $APP"
